
export const SAVE_SELECTED_ITEM = 'SAVE_SELECTED_ITEM';
export const REMOVE_SELECTED_ITEM = 'REMOVE_SELECTED_ITEM';
export const ADD_AVAILABLE_ITEM = 'ADD_AVAILABLE_ITEM';
export const REMOVE_AVAILABLE_ITEM = 'REMOVE_AVAILABLE_ITEM';


